---
# tasks file for lamp

- name: Create a Download Dir
  command: mkdir -p /opt/source/wordpress

- name: Download Wordpress Tarballs
  get_url: url="https://wordpress.org/latest.tar.gz" dest=/opt/source/wordpress/wordpress.tar.gz 


- name: Extract Wordpress TarBall
  command: "tar -zxf /opt/source/wordpress/wordpress.tar.gz  -C /var/www/html/ --strip-components 1"


- name: Setting Up Config
  template: src=templates/wp-config-sample.php.j2 dest=/var/www/html/wp-config.php mode=0644

- name: Set the Right OS Permission
  command: "chown -R root:www-data /var/www/html"
  notify:
  - Restart Apache
