---
# tasks file for lamp-dep

- name: Install Lamp Stack Dep. Packages 
  apt: name={{item}} state=present
  with_items:
  - apache2
  - mysql-server
  - mysql-client
  - python3-mysqldb
  - libmysqlclient-dev
  - php
  - libapache2-mod-php
  - php-mysql
  - python3-pip

- name: Make sure pymysql is present  
  shell: "pip3 install pymysql"

- name: Bring Up MariaDB
  service: name=mysql state=started enabled=True

- name: Deploy MySQL Config
  template: src=templates/my.cnf.j2 dest=/root/.my.cnf
  run_once: true 

- name: Deploy MySQL Config Updated
  template: src=templates/my.cnf-2.j2 dest=/root/.my.cnf


- name: Remove Annomous Users
  command: 'mysql -ne "{{item}}"'
  with_items:
    - DELETE FROM mysql.user WHERE User=''
  changed_when: False



- name: Disallow Root Login from Remote
  command: 'mysql -ne "{{item}}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ( 'localhost', '127.0.0.1', '::1')
  changed_when: False



- name: Remove Test Databases & Access
  command: 'mysql -ne "{{item}}"'
  with_items:
    - DROP DATABASE IF EXISTS test
    - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
  changed_when: False


- name: Reload Privilege Tabels
  command: 'mysql -ne "{{item}}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False


