---

- name: Palo Alto Playbook
  hosts: palo
  connection: local

  collections:
    - paloaltonetworks.panos

  tasks:

    - name: Set Hostname
      panos_mgtconfig:
        provider: '{{ palo_provider }}'
        hostname: '{{ hostname }}'
